DB_HOST: 127.0.0.1
DB_NAME: dbname
DB_USER: username
DB_PASSWORD: password
NB_MAX_MYSQL_CLIENT: 50
NB_MAX_PROMISE_IN_LOOP: 50
DEFAULT_GENERATOR_LOCALE: en_US

IS_REMOTE: true

DB_HOST_SOURCE: 8.8.8.8
DB_NAME_SOURCE: source_db
DB_USER_SOURCE: username_source
DB_PASSWORD_SOURCE: password_source
NB_MAX_MYSQL_CLIENT_SOURCE: 50